version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drone_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - drone_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: drone_webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - drone_network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: drone_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: drone_store
      POSTGRES_USER: drone_user
      POSTGRES_PASSWORD: drone_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - drone_network

  redis:
    image: redis:alpine
    container_name: drone_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - drone_network

volumes:
  postgres_data:

networks:
  drone_network:
    driver: bridge 